Layout/FirstArrayElementIndentation:
  EnforcedStyle: 'consistent'

Layout/FirstHashElementIndentation:
  EnforcedStyle: 'consistent'

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  SupportedStyles: 'never'
